name: Release Dify Plugin

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v0.0.1, etc.

permissions:
  contents: write  # Required for creating releases and uploading assets

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Get tag name
      id: tag
      run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Update manifest version
      run: |
        # Extract version from tag (remove 'v' prefix)
        VERSION=${GITHUB_REF#refs/tags/v}
        # Update version in manifest.yaml
        sed -i "s/^version: .*/version: $VERSION/" manifest.yaml
        sed -i "s/^    version: .*/    version: $VERSION/" manifest.yaml
    
    - name: Download Dify Plugin CLI
      run: |
        # Get the latest release of Dify plugin CLI
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/langgenius/dify-plugin-daemon/releases/latest)
        DOWNLOAD_URL=$(echo "$LATEST_RELEASE" | grep -o '"browser_download_url": "[^"]*dify-plugin-linux-amd64[^"]*"' | cut -d'"' -f4)
        
        if [ -z "$DOWNLOAD_URL" ]; then
          echo "Could not find dify-plugin-linux-amd64 in latest release"
          echo "Available assets:"
          echo "$LATEST_RELEASE" | grep '"name":'
          exit 1
        fi
        
        echo "Downloading from: $DOWNLOAD_URL"
        wget -q "$DOWNLOAD_URL" -O dify-plugin
        chmod +x dify-plugin
        
        # Verify the tool works
        ./dify-plugin version
    
    - name: Package Plugin with Dify CLI
      run: |
        # Ensure _assets directory exists and copy icon there if needed
        mkdir -p _assets
        if [ -f "icon.svg" ] && [ ! -f "_assets/icon.svg" ]; then
          cp icon.svg _assets/
        fi
        
        if [ ! -f "_assets/icon.svg" ]; then
          echo "Error: _assets/icon.svg is missing. Icon should be in _assets directory."
          exit 1
        fi
        
        # Create parent directory for packaging (Dify CLI must run from outside plugin dir)
        mkdir -p ../temp-packaging
        
        # Copy the dify-plugin binary to temp-packaging directory
        cp dify-plugin ../temp-packaging/
        
        # Copy the entire plugin directory to temp location
        cp -r . ../temp-packaging/plugin/
        
        # Remove the dify-plugin binary from the copied plugin directory (we don't want it in the package)
        rm -f ../temp-packaging/plugin/dify-plugin
        
        cd ../temp-packaging
        
        # Package the plugin using Dify CLI from outside the plugin directory
        ./dify-plugin plugin package plugin
        
        # Move the generated package back to the workspace
        if [ -f "plugin.difypkg" ]; then
          mv plugin.difypkg "${GITHUB_WORKSPACE}/vertex-embedding-provider-${{ steps.tag.outputs.tag_name }}.difypkg"
        else
          echo "Error: No .difypkg file was created"
          echo "Files in packaging directory:"
          ls -la
          exit 1
        fi
        
        # Return to workspace
        cd "${GITHUB_WORKSPACE}"
        
        echo "Created package: vertex-embedding-provider-${{ steps.tag.outputs.tag_name }}.difypkg"
        ls -la *.difypkg
    
    - name: Generate release notes
      run: |
        cat > release_notes.md << 'EOF'
        # Vertex AI Embedding Provider ${{ steps.tag.outputs.tag_name }}
        
        A Dify plugin that provides text embeddings using Google's text-multilingual-embedding-002 model through Vertex AI.
        
        ## Installation
        
        ### Option 1: Direct URL Installation (Recommended)
        1. In your Dify application, go to **Settings** → **Model Providers**
        2. Click **Install Plugin**  
        3. Enter this GitHub release URL:
           ```
           https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.tag_name }}/vertex-embedding-provider-${{ steps.tag.outputs.tag_name }}.difypkg
           ```
        4. Follow the setup instructions in the README
        
        ### Option 2: Manual Download
        1. Download the `.difypkg` file from the assets below
        2. In Dify, go to **Settings** → **Model Providers** → **Install Plugin** → **Install via Local File**
        3. Upload the downloaded `.difypkg` file
        
        ## What's Included
        - Vertex AI text-multilingual-embedding-002 model support
        - 768-dimensional embeddings
        - Multi-language support (100+ languages)
        - Secure credential management
        
        ## Prerequisites
        - Google Cloud Platform account
        - Vertex AI API enabled
        - Service account with proper permissions
        
        See the [README](https://github.com/${{ github.repository }}/blob/main/README.md) for detailed setup instructions.
        
        ## Package Information
        - **Format**: `.difypkg` (Official Dify Plugin Package)
        - **Version**: ${{ steps.tag.outputs.tag_name }}
        - **Packaged with**: Official Dify Plugin CLI
        EOF
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Vertex AI Embedding Provider ${{ steps.tag.outputs.tag_name }}
        body_path: release_notes.md
        draft: false
        prerelease: ${{ contains(steps.tag.outputs.tag_name, 'alpha') || contains(steps.tag.outputs.tag_name, 'beta') || contains(steps.tag.outputs.tag_name, 'rc') }}
        files: |
          vertex-embedding-provider-${{ steps.tag.outputs.tag_name }}.difypkg
        token: ${{ secrets.GITHUB_TOKEN }} 